{
 "title": "App Python",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_sum,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (http_server_duration_milliseconds_count{service_name=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Server Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (http_server_active_requests{service_name=\"cadastro-de-livros\"})"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_client_duration_milliseconds_sum{service_name=\"$service_name\"} / http_client_duration_milliseconds_count{service_name=\"$service_name\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_client_duration_milliseconds_count{service_name=\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_client_duration_milliseconds_bucket{service_name=\"$service_name\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_status_code, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\", http_status_code=\"200\"}) / sum by(http_status_code, http_method) (http_server_duration_milliseconds_sum{service_name=\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_method) (http_server_duration_milliseconds_count{service_name=\"$service_name\", http_status_code=~\"500|5*\"}) / sum by(http_method) (http_server_duration_milliseconds_count{service_name=\"$service_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_client_duration_milliseconds_count{service_name=\"$service_name\"} / http_client_duration_milliseconds_sum{service_name=\"$service_name\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "filters": [
      {
       "id": "de0c5f28",
       "operator": "=",
       "scope": "span",
       "value": [],
       "valueType": "keyword"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ]
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}